title: OpenEMR
baseurl: https://www.open-emr.org/blog/
theme: openemr
languageCode: en-us
copyright: OEMR
disqusShortname: openemr
googleAnalytics: UA-8316288-7
ignoreFiles:
  - _files%
  - _cache$
taxonomies:
  tag: ""
  category: ""
params:
  # Required theme-specific variables
  mainSiteUrl: https://www.open-emr.org/
  twitterImage: /images/test.jpg
  coverImageStyle: standard
  twitterCardType: summary
  intro: "true"
  headline: OpenEMR Blog
  description: Open source electronic medical record software
  github: "https://github.com/openemr"
  linkedin: ""
  gplus: https://plus.google.com/106799034872780958301
  twitter: https://twitter.com/openemr
  facebook: https://www.facebook.com/OpenEMR-181315115284266
  stackoverflow: ""
  email: blog@oemr.org
  opengraph: true
  shareTwitter: true
  shareFacebook: true
  shareGooglePlus: true
  shareLinkedIn: true
  dateFormat: Mon, Jan 2, 2006
  highlightJsUrl: ""
  highlightJsLocalUrl: ""
  author:
    name: OpenEMR
    twitter: openemr
permainks:
  post: /:filename/

menu:
  main:
    - name: Features
      url: https://www.open-emr.org/wiki/index.php/OpenEMR_Features
      weight: -180
    - name: Demo
      url: https://www.open-emr.org/demo
      weight: -170
    - name: Downloads
      url: https://www.open-emr.org/wiki/index.php/OpenEMR_Downloads
      weight: -160
    - name: Blog
      url: https://www.open-emr.org/blog/
      weight: -140
    - name: Wiki
      url: https://www.open-emr.org/wiki/
      weight: -130
    - name: Forum
      url: https://community.open-emr.org
      weight: -120
    - name: Chat
      url: https://chat.open-emr.org
      weight: -110
